### ISSUE TITLE
Missing information in documentation?

### ISSUE THREAD

**Issue by bbarman4u** [yagoluiz/sonar-dotnet-vscode#6]
Looks like its missing instruction to install or enable the dotnet scanner tool first 
Here is the [link](https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-msbuild/) I used to download and install the scanner before the plugin steps would work.
Specifically, I used the below step to install the utility on windows -
`dotnet tool install --global dotnet-sonarscanner`

Good Job BTW on the extension.

**Comment by yagoluiz** [comment]
@bbarman4u thanks! Docs update in #7
