### ISSUE TITLE
Make organizationKey optional

### ISSUE THREAD

**Issue by HorstBaerbel** [yagoluiz/sonar-dotnet-vscode#9]
When using a local SonarQube installation / docker service it is not used and the extension must not send "/o:<key>". There is currently no way to turn it off though.

Additionally there is a warning about a missing "organisation" key that should probably not be there:
![sonarqube_ext_error](https://user-images.githubusercontent.com/1310747/94841019-aee70000-0419-11eb-870b-6ae9566571f3.png)

**Comment by Qrbaker** [comment]
As a workaround, you can set the key value to `default-organization`.

**Comment by Qrbaker** [comment]
@HorstBaerbel I made a PR that fixes this: https://github.com/yagoluiz/sonar-dotnet-vscode/pull/13 but while you wait you can do it manually (see my last comment)
